package org.cs3.pl.astvisitor;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.Vector;

import org.cs3.pl.fileops.PrologWriterAction;

/**
 * Implements the FQNManager interface, translating fqn(...) terms to
 * local IDs. local2FQN facts are generated by getFQNMapping.
 *  
 * @author schulzs1
 * @inheritDoc
 */
public class LocalIDFQNTranslator implements FQNTranslator {

	Map fqnToIDTable = new TreeMap();
	private IIDGenerator provider;
	
	/**
	 * constructs a new LocalIDFQNManager. The IIDProvider passed will 
	 * be used to generate IDs once new IDs become necessary 
	 * @param resolver
	 */
	
	public LocalIDFQNTranslator(LocalIDGenerator provider){
		this.provider = provider;
	}
	
	public List getFQNMapping() {
		
			Vector list = new Vector();
			
			list.add(PrologWriterAction.newSetInterpret(false));
			
			
			synchronized (fqnToIDTable){
				Collection c = fqnToIDTable.keySet();
				
				for (Iterator iter = c.iterator(); iter.hasNext();) {
					String key = (String) iter.next();
					PrologWriterAction plwa = PrologWriterAction.newWriteFact("local2FQN", 
							new String [] {(String) fqnToIDTable.get(key), key});
					list.add(plwa);
				}
			}
			
			list.add(PrologWriterAction.newSetInterpret(true));
			
			return list;
		
	}

	public String transformFQN(String string) {
		
		synchronized (fqnToIDTable){
			if (!fqnToIDTable.containsKey(string)){
				fqnToIDTable.put(string, provider.getID());
			}
			return (String) fqnToIDTable.get(string);
		}
	}
}
