/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cs3_pl_prolog_ConsoleIOSession */

#ifndef _Included_org_cs3_pl_prolog_ConsoleIOSession
#define _Included_org_cs3_pl_prolog_ConsoleIOSession
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SOCKET_CONNECT_TIMEOUT */
/* Inaccessible static: SOCKET_ALIVE_TIMEOUT */
/* Inaccessible static: port */
/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    createEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_createEngine
  (JNIEnv *, jobject);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    createConsoleStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_createConsoleStruct
  (JNIEnv *, jobject);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    createStreamInC
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_createStreamInC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    unifyWithTerm
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_unifyWithTerm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    setStream
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_setStream
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    deleteConsoleStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_deleteConsoleStruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cs3_pl_prolog_ConsoleIOSession
 * Method:    deleteEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cs3_pl_prolog_ConsoleIOSession_deleteEngine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
