/* Generated By:JJTree: Do not edit this line. ASTInteger.java */

package org.cs3.pl.parser.internal.term;

public class ASTInteger extends SimpleNode {
	protected String value;

	public ASTInteger(int id) {
		super(id);
	}

	public ASTInteger(PrologTermParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(PrologTermParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toString() {
		return super.toString() + " (" + getImage() + ")";
	}

	protected void synthesizeImage(StringBuffer sb) {
		sb.append(getValue());

	}

	public String getValue() {
		if (value == null) {
			if(copy){
				;//throw new Error("!!!OOPS, my value is gone...!!!");
				value = "!!!OOPS, my value is gone...!!!";
			}
			else{
				value = getImage();
			}
		}
		return value;
	}

	public SimpleNode createShallowCopy() {
		ASTInteger copy = new ASTInteger(parser, id);
		copy.copy = true;
		copy.value = getValue();
		return copy;
	}
	public int getArity() {	
		return 0;
	}
	
}
