/*****************************************************************************
 * This file is part of the Prolog Development Tool (PDT)
 * 
 * Author: Lukas Degener (among others) 
 * E-mail: degenerl@cs.uni-bonn.de
 * WWW: http://roots.iai.uni-bonn.de/research/pdt 
 * Copyright (C): 2004-2006, CS Dept. III, University of Bonn
 * 
 * All rights reserved. This program is  made available under the terms 
 * of the Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 * 
 * In addition, you may at your option use, modify and redistribute any
 * part of this program under the terms of the GNU Lesser General Public
 * License (LGPL), version 2.1 or, at your option, any later version of the
 * same license, as long as
 * 
 * 1) The program part in question does not depend, either directly or
 *   indirectly, on parts of the Eclipse framework and
 *   
 * 2) the program part in question does not include files that contain or
 *   are derived from third-party work and are therefor covered by special
 *   license agreements.
 *   
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *   
 * ad 1: A program part is said to "depend, either directly or indirectly,
 *   on parts of the Eclipse framework", if it cannot be compiled or cannot
 *   be run without the help or presence of some part of the Eclipse
 *   framework. All java classes in packages containing the "pdt" package
 *   fragment in their name fall into this category.
 *   
 * ad 2: "Third-party code" means any code that was originaly written as
 *   part of a project other than the PDT. Files that contain or are based on
 *   such code contain a notice telling you so, and telling you the
 *   particular conditions under which they may be used, modified and/or
 *   distributed.
 ****************************************************************************/

/* Generated By:JJTree: Do not edit this line. PrologTermParserTreeConstants.java */

package org.cs3.pl.parser.internal.term;

public interface PrologTermParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTMEMBER = 1;
  public int JJTVOID = 2;
  public int JJTINFIXTERM = 3;
  public int JJTPREFIXTERM = 4;
  public int JJTBRACESTERM = 5;
  public int JJTLISTTERM = 6;
  public int JJTPARANTHESISTERM = 7;
  public int JJTCOMPOUNDTERM = 8;
  public int JJTCUT = 9;
  public int JJTSTRING = 10;
  public int JJTVARIABLE = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTINTEGER = 13;
  public int JJTFLOAT = 14;
  public int JJTCHARACTERS = 15;
  public int JJTPREFIXOPERATOR = 16;
  public int JJTINFIXOPERATOR = 17;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Member",
    "void",
    "InfixTerm",
    "PrefixTerm",
    "BracesTerm",
    "ListTerm",
    "ParanthesisTerm",
    "CompoundTerm",
    "Cut",
    "String",
    "Variable",
    "Identifier",
    "Integer",
    "Float",
    "Characters",
    "PrefixOperator",
    "InfixOperator",
  };
}
