/*****************************************************************************
 * This file is part of the Prolog Development Tool (PDT)
 * 
 * Author: Lukas Degener (among others) 
 * E-mail: degenerl@cs.uni-bonn.de
 * WWW: http://roots.iai.uni-bonn.de/research/pdt 
 * Copyright (C): 2004-2006, CS Dept. III, University of Bonn
 * 
 * All rights reserved. This program is  made available under the terms 
 * of the Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 * 
 * In addition, you may at your option use, modify and redistribute any
 * part of this program under the terms of the GNU Lesser General Public
 * License (LGPL), version 2.1 or, at your option, any later version of the
 * same license, as long as
 * 
 * 1) The program part in question does not depend, either directly or
 *   indirectly, on parts of the Eclipse framework and
 *   
 * 2) the program part in question does not include files that contain or
 *   are derived from third-party work and are therefor covered by special
 *   license agreements.
 *   
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *   
 * ad 1: A program part is said to "depend, either directly or indirectly,
 *   on parts of the Eclipse framework", if it cannot be compiled or cannot
 *   be run without the help or presence of some part of the Eclipse
 *   framework. All java classes in packages containing the "pdt" package
 *   fragment in their name fall into this category.
 *   
 * ad 2: "Third-party code" means any code that was originaly written as
 *   part of a project other than the PDT. Files that contain or are based on
 *   such code contain a notice telling you so, and telling you the
 *   particular conditions under which they may be used, modified and/or
 *   distributed.
 ****************************************************************************/

/* Generated By:JJTree&JavaCC: Do not edit this line. PrologTermParserConstants.java */
package org.cs3.pl.parser.internal.term;

public interface PrologTermParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int SINGLE_LINE_COMMENT = 3;
  int MULTI_LINE_COMMENT = 4;
  int OPERATOR = 6;
  int OPBODY = 7;
  int DECIMAL_LITERAL = 8;
  int BIN_LITERAL = 9;
  int OCT_LITERAL = 10;
  int HEX_LITERAL = 11;
  int FLOATING_POINT_LITERAL = 12;
  int EXPONENT = 13;
  int CHARACTER_ATOM = 14;
  int STRING_LITERAL = 15;
  int VARIABLE = 16;
  int IDENTIFIER = 17;
  int UNDERLINE = 18;
  int UPPERLETTER = 19;
  int DIGIT = 20;
  int LOWERLETTER = 21;
  int DOLLAR = 22;
  int CUT = 23;
  int DOT = 24;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 5>",
    "<OPERATOR>",
    "<OPBODY>",
    "<DECIMAL_LITERAL>",
    "<BIN_LITERAL>",
    "<OCT_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_ATOM>",
    "<STRING_LITERAL>",
    "<VARIABLE>",
    "<IDENTIFIER>",
    "<UNDERLINE>",
    "<UPPERLETTER>",
    "<DIGIT>",
    "<LOWERLETTER>",
    "\"$\"",
    "\"!\"",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"]\"",
    "\"}\"",
    "\"{\"",
    "\"[\"",
  };

}
