/* Generated By:JJTree: Do not edit this line. PrologTermParserVisitor.java */

package org.cs3.pl.parser.internal.term;

public interface PrologTermParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCompilationUnit node, Object data);
  public Object visit(ASTMember node, Object data);
  public Object visit(ASTInfixTerm node, Object data);
  public Object visit(ASTPrefixTerm node, Object data);
  public Object visit(ASTBracesTerm node, Object data);
  public Object visit(ASTListTerm node, Object data);
  public Object visit(ASTParanthesisTerm node, Object data);
  public Object visit(ASTCompoundTerm node, Object data);
  public Object visit(ASTCut node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTCharacters node, Object data);
  public Object visit(ASTPrefixOperator node, Object data);
  public Object visit(ASTInfixOperator node, Object data);
}
