/* Generated By:JJTree: Do not edit this line. ASTDynamicMultifile.java */

package org.cs3.pl.parser;

public class ASTNamedCall extends SimpleNode implements ASTUnitMember{
  private Token endToken;
private int kind;

public ASTNamedCall(int id) {
    super(id);
  }

  public ASTNamedCall(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
	/* (non-Javadoc)
	 * @see org.cs3.pl.parser.ASTUnitMember#setEndToken(org.cs3.pl.parser.Token)
	 */
	public void setEndToken(Token token) {
		endToken = token;
		
	}

	/* (non-Javadoc)
	 * @see org.cs3.pl.parser.ASTUnitMember#getEndToken(org.cs3.pl.parser.Token)
	 */
	public Token getEndToken() {
		return endToken;
	}

	/**
	 * @return
	 */
	public boolean isDynamic() {
		return kind == PrologParserConstants.DYNAMIC;
	}

	/**
	 * @return
	 */
	public boolean isMultifile() {
		return kind == PrologParserConstants.MULTIFILE;
	}

/**
 * @return Returns the kind.
 */
public int getKind() {
	return kind;
}
/**
 * @param kind The kind to set.
 */
public void setKind(int kind) {
	this.kind = kind;
}
}
