/* Generated By:JJTree: Do not edit this line. ASTPrologVariable.java */
package org.cs3.pl.parser;

public class ASTVariable extends ASTNamedNode implements ASTTerm {
final static public String ANONYMOUS_VAR = "_";
  
//  private Hashtable vars = new Hashtable();
 

  public boolean isAnonymous(){
    return name.equals(ANONYMOUS_VAR);
  }

  public ASTVariable(int id) {
    super(id);
  }
  
  public ASTVariable(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
