/* Generated By:JJTree: Do not edit this line. ASTAtom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.cs3.pl.cterm.internal.parser;

public
class ASTAtom extends ASTNode {
  public ASTAtom(int id) {
    super(id);
  }

  public ASTAtom(CanonicalTermParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CanonicalTermParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=82c0f39a21f38073608b38911e99c4bf (do not edit this line) */
