/* Generated By:JJTree: Do not edit this line. ./CanonicalTermParserTreeConstants.java */

package org.cs3.pl.cterm.internal.parser;

public interface CanonicalTermParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTATOM = 1;
  public int JJTNIL = 2;
  public int JJTVARIABLE = 3;
  public int JJTCOMPOUND = 4;
  public int JJTINTEGER = 5;
  public int JJTFLOAT = 6;
  public int JJTSTRING = 7;


  public String[] jjtNodeName = {
    "void",
    "Atom",
    "Nil",
    "Variable",
    "Compound",
    "Integer",
    "Float",
    "String",
  };
}
