/* Generated By:JJTree: Do not edit this line. .\CanonicalTermParserTreeConstants.java */

package org.cs3.pl.cterm.internal.parser;

public interface CanonicalTermParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTATOM = 1;
  public int JJTVARIABLE = 2;
  public int JJTCOMPOUND = 3;
  public int JJTINTEGER = 4;
  public int JJTFLOAT = 5;


  public String[] jjtNodeName = {
    "void",
    "Atom",
    "Variable",
    "Compound",
    "Integer",
    "Float",
  };
}
