/* Generated By:JJTree&JavaCC: Do not edit this line. CanonicalTermParserConstants.java */
package org.cs3.pl.cterm.internal.parser;

public interface CanonicalTermParserConstants {

  int EOF = 0;
  int LPAREN = 7;
  int RPAREN = 8;
  int COMMA = 9;
  int DOT = 10;
  int LSQB = 11;
  int RSQB = 12;
  int LBRC = 13;
  int RBRC = 14;
  int CUT = 15;
  int ATOM_IDENTIFIER = 16;
  int VARIABLE_IDENTIFIER = 17;
  int LETTER = 18;
  int LC_LETTER = 19;
  int UNICODE_LETTER = 20;
  int GRAPHIC = 21;
  int UC_LETTER = 22;
  int DIGIT = 23;
  int DECIMAL_LITERAL = 24;
  int BIN_LITERAL = 25;
  int OCT_LITERAL = 26;
  int HEX_LITERAL = 27;
  int FLOATING_POINT_LITERAL = 28;
  int EXPONENT = 29;
  int QUOTED_ATOM = 30;
  int QUOTED_STRING = 31;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "<ATOM_IDENTIFIER>",
    "<VARIABLE_IDENTIFIER>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UNICODE_LETTER>",
    "<GRAPHIC>",
    "<UC_LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<BIN_LITERAL>",
    "<OCT_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<QUOTED_ATOM>",
    "<QUOTED_STRING>",
  };

}
