/* Generated By:JJTree: Do not edit this line. ./CanonicalTermParserVisitor.java */

package org.cs3.pl.cterm.internal.parser;

public interface CanonicalTermParserVisitor
{
  public Object visit(ASTNode node, Object data);
  public Object visit(ASTAtom node, Object data);
  public Object visit(ASTNil node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTCompound node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTString node, Object data);
}
