/* Generated By:JJTree&JavaCC: Do not edit this line. CanonicalTermParserConstants.java */
package org.cs3.pl.cterm.internal.parser;

public interface CanonicalTermParserConstants {

  int EOF = 0;
  int LPAREN = 7;
  int RPAREN = 8;
  int COMMA = 9;
  int DOT = 10;
  int ATOM_IDENTIFIER = 11;
  int VARIABLE_IDENTIFIER = 12;
  int LETTER = 13;
  int LC_LETTER = 14;
  int UC_LETTER = 15;
  int DIGIT = 16;
  int DECIMAL_LITERAL = 17;
  int BIN_LITERAL = 18;
  int OCT_LITERAL = 19;
  int HEX_LITERAL = 20;
  int FLOATING_POINT_LITERAL = 21;
  int EXPONENT = 22;
  int QUOTED_ATOM = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<ATOM_IDENTIFIER>",
    "<VARIABLE_IDENTIFIER>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UC_LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<BIN_LITERAL>",
    "<OCT_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<QUOTED_ATOM>",
  };

}
