/* Generated By:JJTree: Do not edit this line. ASTClause.java */

package org.cs3.pl.parser.internal.classic;


public class ASTClause extends ASTNamedNode {
	
	private String module;
	private Token endToken;
	private ASTHead head;
	private ASTBody body;
	
  public ASTClause(int id) {
    super(id);
  }

  public ASTClause(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getName() {
  	return getHead().getName();
  }

  public int getArity() {
	  return getHead().getArity();
  }

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public ASTPredicateArgs getArgs() {
		return getHead().getArguments();
	}

	public void setHead(ASTHead head) {
		this.head=head;
		
	}

	public void setBody(ASTBody body) {
		this.body=body;
		
	}

	public ASTBody getBody() {
		return body;
	}

	public ASTHead getHead() {
		return head;
	}

	
	
}
