/* Generated By:JJTree: Do not edit this line. ASTFunctorVariableModule.java */

package org.cs3.pl.parser.internal.classic;

public class ASTFunctorVariableModule extends ASTFunctor {
  public ASTFunctorVariableModule(int id) {
    super(id);
  }

  public ASTFunctorVariableModule(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
	public String getModuleName() {
		return ((ASTVariable)children[0]).getName();
	}

}
