/* Generated By:JJTree: Do not edit this line. ASTHead.java */

package org.cs3.pl.parser.internal.classic;

public class ASTHead extends ASTNamedNode {
  

private ASTPredicateArgs args;

public ASTHead(int id) {
    super(id);
  }

  public ASTHead(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

	public void setArguments(ASTPredicateArgs args) {
		this.args=args;
		
	}

	public ASTPredicateArgs getArguments() {
		return args;
	}

	public int getArity() {
		ASTPredicateArgs a = getArguments();
		if(a==null)return 0;
		return a.jjtGetNumChildren();
	}

	
}
