/* Generated By:JJTree: Do not edit this line. ASTSequence.java */

package org.cs3.pl.parser.internal.classic;

public class ASTSequence extends SimpleNode implements ASTTerm {
  public ASTSequence(int id) {
    super(id);
  }

  public ASTSequence(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
