/*****************************************************************************
 * This file is part of the Prolog Development Tool (PDT)
 * 
 * Author: Lukas Degener (among others) 
 * E-mail: degenerl@cs.uni-bonn.de
 * WWW: http://roots.iai.uni-bonn.de/research/pdt 
 * Copyright (C): 2004-2006, CS Dept. III, University of Bonn
 * 
 * All rights reserved. This program is  made available under the terms 
 * of the Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 * 
 * In addition, you may at your option use, modify and redistribute any
 * part of this program under the terms of the GNU Lesser General Public
 * License (LGPL), version 2.1 or, at your option, any later version of the
 * same license, as long as
 * 
 * 1) The program part in question does not depend, either directly or
 *   indirectly, on parts of the Eclipse framework and
 *   
 * 2) the program part in question does not include files that contain or
 *   are derived from third-party work and are therefor covered by special
 *   license agreements.
 *   
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *   
 * ad 1: A program part is said to "depend, either directly or indirectly,
 *   on parts of the Eclipse framework", if it cannot be compiled or cannot
 *   be run without the help or presence of some part of the Eclipse
 *   framework. All java classes in packages containing the "pdt" package
 *   fragment in their name fall into this category.
 *   
 * ad 2: "Third-party code" means any code that was originaly written as
 *   part of a project other than the PDT. Files that contain or are based on
 *   such code contain a notice telling you so, and telling you the
 *   particular conditions under which they may be used, modified and/or
 *   distributed.
 ****************************************************************************/

/* Generated By:JJTree&JavaCC: Do not edit this line. PrologParserConstants.java */
package org.cs3.pl.parser.internal.classic;

public interface PrologParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int DYNAMIC = 10;
  int MULTIFILE = 11;
  int INIT = 12;
  int MODULE_TRANSPARENT = 13;
  int VOLATILE = 14;
  int ASSIGN = 15;
  int METAASSIGN = 16;
  int GT = 17;
  int LT = 18;
  int CUT = 19;
  int ARROW = 20;
  int IF = 21;
  int SOFTCUT = 22;
  int QUERY = 23;
  int CLAUSEDEF = 24;
  int COLON = 25;
  int EQ = 26;
  int EQ2 = 27;
  int EQ3 = 28;
  int EQ4 = 29;
  int NEQ = 30;
  int NEQ2 = 31;
  int IS = 32;
  int LE = 33;
  int LE2 = 34;
  int GE = 35;
  int GE2 = 36;
  int NE = 37;
  int PLUS = 38;
  int MINUS = 39;
  int STAR = 40;
  int NOTPROVABLE = 41;
  int MOD = 42;
  int LSHIFT = 43;
  int RSIGNEDSHIFT = 44;
  int DOLLAR = 45;
  int SLASH = 46;
  int POINTER = 47;
  int AT = 48;
  int DIVISION = 49;
  int BITAND = 50;
  int BITOR = 51;
  int BITNOT = 52;
  int BITXOR = 53;
  int DECIMAL_LITERAL = 54;
  int BIN_LITERAL = 55;
  int OCT_LITERAL = 56;
  int HEX_LITERAL = 57;
  int FLOATING_POINT_LITERAL = 58;
  int EXPONENT = 59;
  int CHARACTER_ATOM = 60;
  int STRING_LITERAL = 61;
  int ZERO_APO_REST = 62;
  int VARIABLE = 63;
  int IDENTIFIER = 64;
  int UNDERLINE = 65;
  int UPPERLETTER = 66;
  int DIGIT = 67;
  int LOWERLETTER = 68;
  int LPAREN = 69;
  int RPAREN = 70;
  int LBRACE = 71;
  int RBRACE = 72;
  int LBRACKET = 73;
  int RBRACKET = 74;
  int SEMICOLON = 75;
  int COMMA = 76;
  int DOT = 77;
  int LISTSEP = 78;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 9>",
    "\"dynamic\"",
    "\"multifile\"",
    "\"initialization\"",
    "\"module_transparent\"",
    "\"volatile\"",
    "\"=\"",
    "\"=..\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"-->\"",
    "\"->\"",
    "\"*->\"",
    "\"?-\"",
    "\":-\"",
    "\":\"",
    "\"==\"",
    "\"=:=\"",
    "\"=\\\\=\"",
    "\"=@=\"",
    "\"\\\\=\"",
    "\"\\\\==\"",
    "\"is\"",
    "\"<=\"",
    "\"=<\"",
    "\">=\"",
    "\"=>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"\\\\+\"",
    "\"mod\"",
    "\"<<\"",
    "\">>\"",
    "\"$\"",
    "\"/\"",
    "\"^\"",
    "\"@\"",
    "\"//\"",
    "\"/\\\\\"",
    "\"\\\\//\"",
    "\"\\\\/\"",
    "\"xor\"",
    "<DECIMAL_LITERAL>",
    "<BIN_LITERAL>",
    "<OCT_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_ATOM>",
    "<STRING_LITERAL>",
    "<ZERO_APO_REST>",
    "<VARIABLE>",
    "<IDENTIFIER>",
    "<UNDERLINE>",
    "<UPPERLETTER>",
    "<DIGIT>",
    "<LOWERLETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"|\"",
  };

}
