/*****************************************************************************
 * This file is part of the Prolog Development Tool (PDT)
 * 
 * Author: Lukas Degener (among others) 
 * E-mail: degenerl@cs.uni-bonn.de
 * WWW: http://roots.iai.uni-bonn.de/research/pdt 
 * Copyright (C): 2004-2006, CS Dept. III, University of Bonn
 * 
 * All rights reserved. This program is  made available under the terms 
 * of the Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 * 
 * In addition, you may at your option use, modify and redistribute any
 * part of this program under the terms of the GNU Lesser General Public
 * License (LGPL), version 2.1 or, at your option, any later version of the
 * same license, as long as
 * 
 * 1) The program part in question does not depend, either directly or
 *   indirectly, on parts of the Eclipse framework and
 *   
 * 2) the program part in question does not include files that contain or
 *   are derived from third-party work and are therefor covered by special
 *   license agreements.
 *   
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *   
 * ad 1: A program part is said to "depend, either directly or indirectly,
 *   on parts of the Eclipse framework", if it cannot be compiled or cannot
 *   be run without the help or presence of some part of the Eclipse
 *   framework. All java classes in packages containing the "pdt" package
 *   fragment in their name fall into this category.
 *   
 * ad 2: "Third-party code" means any code that was originaly written as
 *   part of a project other than the PDT. Files that contain or are based on
 *   such code contain a notice telling you so, and telling you the
 *   particular conditions under which they may be used, modified and/or
 *   distributed.
 ****************************************************************************/

/* Generated By:JJTree: Do not edit this line. PrologParserTreeConstants.java */

package org.cs3.pl.parser.internal.classic;

public interface PrologParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTOR = 2;
  public int JJTFUNCTORVARIABLEMODULE = 3;
  public int JJTVARIABLE = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTNAMEDCALL = 6;
  public int JJTCALL = 7;
  public int JJTPREDICATESIGNATURE = 8;
  public int JJTCLAUSE = 9;
  public int JJTHEAD = 10;
  public int JJTPREDICATEARGS = 11;
  public int JJTCOMPOUND = 12;
  public int JJTCUT = 13;
  public int JJTSEQUENCE = 14;
  public int JJTLIST = 15;
  public int JJTBRACES = 16;
  public int JJTPARENTHESIS = 17;
  public int JJTRESTTOKENS = 18;
  public int JJTINTATOM = 19;
  public int JJTFLOATATOM = 20;
  public int JJTSTRINGATOM = 21;
  public int JJTCHARATOM = 22;
  public int JJTBODY = 23;
  public int JJTSEPARATOR = 24;
  public int JJTBINARYOP = 25;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Functor",
    "FunctorVariableModule",
    "Variable",
    "Identifier",
    "NamedCall",
    "Call",
    "PredicateSignature",
    "Clause",
    "Head",
    "PredicateArgs",
    "Compound",
    "Cut",
    "Sequence",
    "List",
    "Braces",
    "Parenthesis",
    "RestTokens",
    "IntAtom",
    "FloatAtom",
    "StringAtom",
    "CharAtom",
    "Body",
    "Separator",
    "BinaryOp",
  };
}
