/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.java */

package org.cs3.pl.parser.internal.term;

public class ASTCompilationUnit extends SimpleNode {

	String filename;
	public ASTCompilationUnit(int id) {
		super(id);
	}

	public ASTCompilationUnit(PrologTermParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(PrologTermParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public String getModuleName(){
		String result = "user";
		if (jjtGetNumChildren()>0) {
			ASTMember m = (ASTMember) children[0];
			if (m.isDirective()) {
				if (m.bodyLiterals[0] instanceof ASTCompoundTerm) {
					ASTCompoundTerm cmp = (ASTCompoundTerm) m.bodyLiterals[0];
					if ("module".equals(cmp.getLabel())) {
						result = cmp.getArguments()[0].getImage();
					}
				}
			}
		}
		return result;
	}

	protected void synthesizeImage(StringBuffer sb) {
		for (int i = 0;children!=null&& i < children.length; i++) {
			SimpleNode c = (SimpleNode) children[i];
			if(i>0){
				sb.append("\n");
			}
			c.synthesizeImage(sb);						
		}
		
	}

	public SimpleNode createShallowCopy() {
		ASTCompilationUnit copy = new ASTCompilationUnit(parser,id);
		copy.copy=true;
		copy.filename=this.getFileName();		
		return copy;
	}

	private String getFileName() {
		// TODO Auto-generated method stub
		return null;
	}
}
