/* Generated By:JJTree: Do not edit this line. ASTFloat.java */

package org.cs3.pl.parser.internal.term;

public class ASTFloat extends SimpleNode {
	String value;

	public ASTFloat(int id) {
		super(id);
	}

	public ASTFloat(PrologTermParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(PrologTermParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toString() {
		return super.toString() + " (" + getImage() + ")";
	}

	protected void synthesizeImage(StringBuffer sb) {
		sb.append(getValue());
		
	}

	public SimpleNode createShallowCopy() {
		ASTFloat copy = new ASTFloat(parser,id);
		copy.copy=true;
		copy.value=getValue();
		return copy;
	}
	
	public int getArity() {
		return 0;
	
	}
	
}
