/* Generated By:JJTree&JavaCC: Do not edit this line. PrologTermParserConstants.java */
package org.cs3.pl.parser.internal.term;

public interface PrologTermParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int SINGLE_LINE_COMMENT = 3;
  int MULTI_LINE_COMMENT = 4;
  int OPERATOR = 6;
  int OPBODY = 7;
  int DECIMAL_LITERAL = 8;
  int BIN_LITERAL = 9;
  int OCT_LITERAL = 10;
  int HEX_LITERAL = 11;
  int FLOATING_POINT_LITERAL = 12;
  int EXPONENT = 13;
  int CHARACTER_ATOM = 14;
  int STRING_LITERAL = 15;
  int FAKEEOF = 16;
  int VARIABLE = 17;
  int IDENTIFIER = 18;
  int UNDERLINE = 19;
  int UPPERLETTER = 20;
  int DIGIT = 21;
  int LOWERLETTER = 22;
  int DOLLAR = 23;
  int CUT = 24;
  int DOT = 25;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 5>",
    "<OPERATOR>",
    "<OPBODY>",
    "<DECIMAL_LITERAL>",
    "<BIN_LITERAL>",
    "<OCT_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_ATOM>",
    "<STRING_LITERAL>",
    "<FAKEEOF>",
    "<VARIABLE>",
    "<IDENTIFIER>",
    "<UNDERLINE>",
    "<UPPERLETTER>",
    "<DIGIT>",
    "<LOWERLETTER>",
    "\"$\"",
    "\"!\"",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"]\"",
    "\"}\"",
    "\"{\"",
    "\"[\"",
  };

}
