/* Generated By:JJTree&JavaCC: Do not edit this line. PrologTermParserTokenManager.java */
package org.cs3.pl.parser.internal.term;
import java.io.InputStream;
import java.io.FileInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.ArrayList;

public class PrologTermParserTokenManager implements PrologTermParserConstants
{
void CommonTokenAction(Token t){
         t.beginOffset = input_stream.getBeginOffset();
         t.endOffset = input_stream.getEndOffset();
}
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 6;
            return -1;
         }
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 6;
            return 158;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 6;
            return 318;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 24);
      case 36:
         return jjStartNfaWithStates_0(0, 6, 318);
      case 40:
         return jjStopAtPos(0, 26);
      case 41:
         return jjStopAtPos(0, 28);
      case 44:
         return jjStopAtPos(0, 6);
      case 46:
         return jjStopAtPos(0, 25);
      case 47:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 91:
         return jjStopAtPos(0, 32);
      case 93:
         return jjStopAtPos(0, 29);
      case 123:
         return jjStopAtPos(0, 31);
      case 125:
         return jjStopAtPos(0, 30);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 318;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 158:
               case 112:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 318:
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(58, 59);
                  break;
               case 0:
                  if ((0xfc00bc1000000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                     jjCheckNAddStates(0, 9);
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(10, 31);
                  else if (curChar == 34)
                     jjCheckNAddStates(32, 35);
                  else if (curChar == 37)
                  {
                     if (kind > 3)
                        kind = 3;
                     jjCheckNAddStates(36, 38);
                  }
                  if (curChar == 47)
                     jjAddStates(39, 40);
                  else if (curChar == 62)
                     jjCheckNAddTwoStates(64, 62);
                  else if (curChar == 42)
                     jjAddStates(41, 42);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(134, 62);
                  else if (curChar == 58)
                     jjCheckNAddStates(43, 45);
                  else if (curChar == 61)
                     jjCheckNAddStates(46, 51);
                  else if (curChar == 36)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAddTwoStates(58, 59);
                  }
                  else if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 60)
                     jjCheckNAdd(17);
                  else if (curChar == 63)
                     jjCheckNAdd(15);
                  break;
               case 1:
                  if (curChar != 37)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(36, 38);
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(36, 38);
                  break;
               case 3:
                  if ((0x2400L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 4:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if ((0xfc00bc1000000000L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 15:
                  if (curChar == 45 && kind > 6)
                     kind = 6;
                  break;
               case 16:
                  if (curChar == 63)
                     jjCheckNAdd(15);
                  break;
               case 17:
                  if (curChar == 60 && kind > 6)
                     kind = 6;
                  break;
               case 18:
                  if (curChar == 60)
                     jjCheckNAdd(17);
                  break;
               case 37:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (kind > 8)
                     kind = 8;
                  break;
               case 39:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 40:
               case 44:
                  if (curChar == 34)
                     jjCheckNAddStates(32, 35);
                  break;
               case 41:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(32, 35);
                  break;
               case 43:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(32, 35);
                  break;
               case 45:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 34 && kind > 15)
                     kind = 15;
                  break;
               case 47:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(52, 56);
                  break;
               case 48:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(32, 35);
                  break;
               case 49:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(48);
                  break;
               case 52:
                  if (kind > 16)
                     kind = 16;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 57:
                  if (curChar != 36)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(58, 59);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddStates(57, 59);
                  break;
               case 62:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 63:
                  if (curChar == 61)
                     jjCheckNAdd(17);
                  break;
               case 64:
                  if (curChar == 61 && kind > 6)
                     kind = 6;
                  break;
               case 65:
                  if (curChar == 62)
                     jjCheckNAdd(64);
                  break;
               case 66:
                  if (curChar == 61)
                     jjCheckNAddStates(46, 51);
                  break;
               case 69:
                  if (curChar == 58)
                     jjCheckNAdd(64);
                  break;
               case 70:
                  if (curChar == 46 && kind > 6)
                     kind = 6;
                  break;
               case 71:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 114:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 61)
                     jjCheckNAdd(64);
                  break;
               case 116:
                  if (curChar == 43 && kind > 6)
                     kind = 6;
                  break;
               case 132:
                  if (curChar == 58)
                     jjCheckNAddStates(43, 45);
                  break;
               case 133:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(134, 62);
                  break;
               case 134:
               case 155:
                  if (curChar == 45)
                     jjCheckNAdd(62);
                  break;
               case 153:
                  if (curChar == 42)
                     jjAddStates(41, 42);
                  break;
               case 154:
                  if (curChar == 42 && kind > 6)
                     kind = 6;
                  break;
               case 156:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(64, 62);
                  break;
               case 157:
                  if (curChar == 47)
                     jjAddStates(39, 40);
                  break;
               case 159:
                  if (curChar == 39)
                     jjCheckNAddStates(10, 31);
                  break;
               case 161:
                  if (curChar == 39 && kind > 6)
                     kind = 6;
                  break;
               case 164:
                  if ((0xfc00bc1000000000L & l) != 0L)
                     jjCheckNAdd(161);
                  break;
               case 180:
                  if (curChar == 60)
                     jjCheckNAdd(161);
                  break;
               case 181:
                  if (curChar == 60)
                     jjCheckNAdd(180);
                  break;
               case 182:
                  if (curChar == 45)
                     jjCheckNAdd(161);
                  break;
               case 183:
                  if (curChar == 63)
                     jjCheckNAdd(182);
                  break;
               case 192:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAddStates(60, 63);
                  break;
               case 194:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(60, 63);
                  break;
               case 195:
                  if (curChar == 39)
                     jjCheckNAddStates(60, 63);
                  break;
               case 196:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 39 && kind > 14)
                     kind = 14;
                  break;
               case 256:
                  if (curChar == 47)
                     jjAddStates(64, 65);
                  break;
               case 257:
                  if (curChar == 47)
                     jjCheckNAdd(161);
                  break;
               case 259:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(260, 261);
                  break;
               case 260:
                  if (curChar == 62)
                     jjCheckNAdd(161);
                  break;
               case 261:
                  if (curChar == 61)
                     jjCheckNAdd(161);
                  break;
               case 262:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(260, 263);
                  break;
               case 263:
               case 270:
                  if (curChar == 45)
                     jjCheckNAdd(260);
                  break;
               case 265:
                  if (curChar == 43)
                     jjCheckNAdd(161);
                  break;
               case 266:
                  if (curChar == 61)
                     jjCheckNAdd(261);
                  break;
               case 268:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 42)
                     jjAddStates(66, 67);
                  break;
               case 271:
                  if (curChar == 42)
                     jjCheckNAdd(161);
                  break;
               case 272:
                  if (curChar == 61)
                     jjCheckNAddStates(68, 73);
                  break;
               case 273:
                  if (curChar == 46)
                     jjCheckNAdd(161);
                  break;
               case 274:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 58)
                     jjCheckNAdd(261);
                  break;
               case 278:
                  if (curChar == 58)
                     jjCheckNAddStates(74, 76);
                  break;
               case 294:
                  if (curChar == 62)
                     jjCheckNAdd(261);
                  break;
               case 295:
                  if (curChar == 61)
                     jjCheckNAdd(180);
                  break;
               case 296:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAddStates(0, 9);
                  break;
               case 297:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(297);
                  break;
               case 299:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 301:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 303:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 304:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(304, 305);
                  break;
               case 305:
                  if (curChar == 46)
                     jjCheckNAdd(306);
                  break;
               case 306:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddTwoStates(306, 307);
                  break;
               case 308:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(309);
                  break;
               case 309:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(309);
                  break;
               case 310:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(310, 311);
                  break;
               case 312:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(313);
                  break;
               case 313:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(313);
                  break;
               case 314:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddTwoStates(314, 315);
                  break;
               case 316:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(317);
                  break;
               case 317:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(317);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 158:
                  if (curChar == 92 && kind > 6)
                     kind = 6;
                  break;
               case 318:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAddTwoStates(58, 59);
                  }
                  if ((0x87fffffeL & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAddStates(57, 59);
                  }
                  break;
               case 0:
                  if ((0x87fffffeL & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAdd(56);
                  }
                  else if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAddTwoStates(58, 59);
                  }
                  else if ((0x1000000050000001L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  if (curChar == 100)
                     jjAddStates(77, 78);
                  else if (curChar == 105)
                     jjCheckNAddTwoStates(118, 131);
                  else if (curChar == 92)
                     jjCheckNAddStates(79, 83);
                  else if (curChar == 109)
                     jjAddStates(84, 87);
                  else if (curChar == 64)
                     jjAddStates(88, 91);
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 53;
                  else if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 2:
                  if (kind > 3)
                     kind = 3;
                  jjAddStates(36, 38);
                  break;
               case 6:
                  if ((0x1000000050000001L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 7:
                  if (curChar == 101 && kind > 6)
                     kind = 6;
                  break;
               case 8:
               case 90:
                  if (curChar == 108)
                     jjCheckNAdd(7);
                  break;
               case 9:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 19:
                  if (curChar == 109 && kind > 6)
                     kind = 6;
                  break;
               case 20:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 108 && kind > 6)
                     kind = 6;
                  break;
               case 23:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 114 && kind > 6)
                     kind = 6;
                  break;
               case 35:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 38:
                  if (kind > 8)
                     kind = 8;
                  break;
               case 41:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(32, 35);
                  break;
               case 42:
                  if (curChar == 92)
                     jjAddStates(92, 94);
                  break;
               case 43:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(32, 35);
                  break;
               case 51:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if (kind > 16)
                     kind = 16;
                  break;
               case 53:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 54:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x87fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(56);
                  break;
               case 56:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(56);
                  break;
               case 57:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(58, 59);
                  break;
               case 58:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(58, 59);
                  break;
               case 59:
                  if ((0x87fffffeL & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddStates(57, 59);
                  break;
               case 60:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddStates(57, 59);
                  break;
               case 61:
                  if (curChar == 64)
                     jjAddStates(88, 91);
                  break;
               case 67:
               case 113:
                  if (curChar == 64)
                     jjCheckNAdd(64);
                  break;
               case 68:
                  if (curChar == 92)
                     jjCheckNAdd(64);
                  break;
               case 72:
                  if (curChar == 109)
                     jjAddStates(84, 87);
                  break;
               case 73:
                  if (curChar == 116 && kind > 6)
                     kind = 6;
                  break;
               case 74:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 91:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 116)
                     jjCheckNAdd(7);
                  break;
               case 98:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 100 && kind > 6)
                     kind = 6;
                  break;
               case 110:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 92)
                     jjCheckNAddStates(79, 83);
                  break;
               case 117:
                  if (curChar == 105)
                     jjCheckNAddTwoStates(118, 131);
                  break;
               case 118:
                  if (curChar == 115 && kind > 6)
                     kind = 6;
                  break;
               case 119:
                  if (curChar == 110 && kind > 6)
                     kind = 6;
                  break;
               case 120:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 135:
                  if (curChar == 100)
                     jjAddStates(77, 78);
                  break;
               case 136:
                  if (curChar == 99 && kind > 6)
                     kind = 6;
                  break;
               case 137:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 117)
                     jjCheckNAdd(118);
                  break;
               case 143:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 160:
                  if (curChar == 114)
                     jjCheckNAdd(161);
                  break;
               case 162:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 163:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if ((0x1000000050000001L & l) != 0L)
                     jjCheckNAdd(161);
                  break;
               case 165:
                  if (curChar == 108)
                     jjCheckNAdd(161);
                  break;
               case 166:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 109)
                     jjCheckNAdd(161);
                  break;
               case 178:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 184:
                  if (curChar == 101)
                     jjCheckNAdd(161);
                  break;
               case 185:
               case 213:
                  if (curChar == 108)
                     jjCheckNAdd(184);
                  break;
               case 186:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(60, 63);
                  break;
               case 193:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(60, 63);
                  break;
               case 198:
                  if (curChar == 109)
                     jjAddStates(95, 98);
                  break;
               case 199:
                  if (curChar == 100)
                     jjCheckNAdd(161);
                  break;
               case 200:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 116)
                     jjCheckNAdd(184);
                  break;
               case 202:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 214:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 116)
                     jjCheckNAdd(161);
                  break;
               case 221:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 100)
                     jjAddStates(99, 100);
                  break;
               case 238:
                  if (curChar == 115)
                     jjCheckNAdd(161);
                  break;
               case 239:
                  if (curChar == 117)
                     jjCheckNAdd(238);
                  break;
               case 240:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 99)
                     jjCheckNAdd(161);
                  break;
               case 251:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 258:
                  if (curChar == 92)
                     jjCheckNAdd(161);
                  break;
               case 264:
                  if (curChar == 92)
                     jjCheckNAddStates(101, 105);
                  break;
               case 267:
               case 277:
                  if (curChar == 64)
                     jjCheckNAdd(261);
                  break;
               case 276:
                  if (curChar == 92)
                     jjCheckNAdd(261);
                  break;
               case 279:
                  if (curChar == 105)
                     jjCheckNAddTwoStates(292, 238);
                  break;
               case 280:
                  if (curChar == 110)
                     jjCheckNAdd(161);
                  break;
               case 281:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 284:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 289:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 290:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 291:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 293:
                  if (curChar == 64)
                     jjAddStates(106, 109);
                  break;
               case 298:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 300:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 302:
                  if (curChar == 120)
                     jjCheckNAdd(303);
                  break;
               case 303:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(303);
                  break;
               case 307:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(110, 111);
                  break;
               case 311:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(112, 113);
                  break;
               case 315:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(114, 115);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjAddStates(36, 38);
                  break;
               case 38:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 41:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(32, 35);
                  break;
               case 52:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 192:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(60, 63);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 318 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x10L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(1, 4);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_2()
{
   return 1;
}
static final int[] jjnextStates = {
   297, 298, 300, 302, 304, 305, 310, 311, 314, 315, 163, 164, 176, 179, 181, 183, 
   191, 192, 193, 196, 197, 198, 237, 256, 259, 262, 264, 269, 272, 278, 279, 293, 
   41, 42, 45, 46, 2, 3, 5, 158, 112, 154, 155, 15, 15, 64, 67, 68, 
   69, 64, 71, 17, 41, 42, 48, 45, 46, 58, 59, 60, 192, 193, 196, 197, 
   257, 258, 270, 271, 180, 274, 261, 275, 276, 277, 261, 182, 182, 141, 152, 112, 
   114, 64, 115, 116, 89, 96, 108, 110, 62, 63, 17, 65, 43, 47, 49, 200, 
   212, 219, 236, 249, 255, 265, 266, 261, 268, 257, 294, 180, 295, 260, 308, 309, 
   312, 313, 316, 317, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, "\44", "\41", "\56", 
"\50", "\54", "\51", "\135", "\175", "\173", "\133", };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "IN_MULTI_LINE_COMMENT", 
   "IN_SINGLE_LINE_COMMENT", 
};
public static final int[] jjnewLexState = {
   -1, -1, 1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x1ff87df41L, 
};
static final long[] jjtoSkip = {
   0x1aL, 
};
static final long[] jjtoSpecial = {
   0x18L, 
};
static final long[] jjtoMore = {
   0x24L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[318];
private final int[] jjstateSet = new int[636];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public PrologTermParserTokenManager(SimpleCharStream stream)
{
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public PrologTermParserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 318; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      CommonTokenAction(matchedToken);
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 5)
         {
            jjmatchedKind = 5;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 5)
         {
            jjmatchedKind = 5;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           CommonTokenAction(matchedToken);
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else 
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
}
