LIBNAME=custom_io
OBJ= $LIBNAME.o
SRC= $(OBJ:.o=.c)

all: $(LIBNAME).so
clean: 
	rm $(OBJ)
	rm $(LIBNAME).so
$(LIBNAME).so: $(OBJ)
	gcc  -Wall -g -undefined dynamic_lookup -dynamiclib -o $(LIBNAME).so $(OBJ)

$(LIBNAME).o: $(LIBNAME).c
	gcc -Wall -g -I/usr/local/lib/swipl/include -fpic -c $(LIBNAME).c
