LIBNAME=custom_io
OBJ= $(LIBNAME).o
SRC= $(OBJ:.o=.c)

all: $(LIBNAME).so
clean: 
	rm $(OBJ)
	rm $(LIBNAME).so
$(LIBNAME).so: $(OBJ)
	gcc  -Wall -g -shared -o $(LIBNAME).so $(OBJ)

$(LIBNAME).o: $(LIBNAME).c
	gcc -Wall -g -I/usr/local/lib/pl-5.6.5/include -fPIC -c $(LIBNAME).c
