!include rules.mk
LIBNAME=custom_io
DLLS=$(LIBNAME).dll
all:	$(DLLS)

$(LIBNAME).dll:	$(LIBNAME).obj
	$(LD) /dll /out:$@ $(LDFLAGS) $(LIBNAME).obj $(TERMLIB) $(PLLIB) $(LIBS)

clean::
	if exist *.obj del *.obj
	if exist *~ del *~

distclean: clean
	-del *.dll *.lib *.exp *.pdb 2>nul

