/* Generated By:JJTree: Do not edit this line. ASTFunctor.java */

package org.cs3.pl.parser;

public class ASTFunctor extends ASTNamedNode {
	
	private String moduleName;
	
	public ASTFunctor(int id) {
		super(id);
	}
	
	public ASTFunctor(PrologParser p, int id) {
		super(p, id);
	}
	
	
	/** Accept the visitor. **/
	public Object jjtAccept(PrologParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	/**
	 * @return Returns the moduleName.
	 */
	public String getModuleName() {
		if (moduleName == null)
			return "user";
		return moduleName;
	}
	/**
	 * @param moduleName The moduleName to set.
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
}
