/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

package org.cs3.pl.parser;

public class ASTIdentifier extends ASTNamedNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
