/* Generated By:JJTree: Do not edit this line. ASTList.java */

package org.cs3.pl.parser;

public class ASTList extends SimpleNode implements ASTTerm {
  public ASTList(int id) {
    super(id);
  }

  public ASTList(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
