/* Generated By:JJTree: Do not edit this line. ASTPredicateArgs.java */

package org.cs3.pl.parser;

public class ASTPredicateArgs extends SimpleNode {
  public ASTPredicateArgs(int id) {
    super(id);
  }

  public ASTPredicateArgs(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
