/* Generated By:JJTree: Do not edit this line. ASTRestTokens.java */

package org.cs3.pl.parser;

public class ASTRestTokens extends ASTNamedNode {
  public ASTRestTokens(int id) {
    super(id);
  }

  public ASTRestTokens(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
