/* Generated By:JJTree: Do not edit this line. PrologParserTreeConstants.java */

package org.cs3.pl.parser;

public interface PrologParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTOR = 2;
  public int JJTFUNCTORVARIABLEMODULE = 3;
  public int JJTVARIABLE = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTNAMEDCALL = 6;
  public int JJTCALL = 7;
  public int JJTPREDICATESIGNATURE = 8;
  public int JJTCLAUSE = 9;
  public int JJTPREDICATEARGS = 10;
  public int JJTCOMPOUND = 11;
  public int JJTCUT = 12;
  public int JJTSEQUENCE = 13;
  public int JJTLIST = 14;
  public int JJTBRACES = 15;
  public int JJTPARENTHESIS = 16;
  public int JJTRESTTOKENS = 17;
  public int JJTINTATOM = 18;
  public int JJTFLOATATOM = 19;
  public int JJTSTRINGATOM = 20;
  public int JJTCHARATOM = 21;
  public int JJTSEPARATOR = 22;
  public int JJTBINARYOP = 23;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Functor",
    "FunctorVariableModule",
    "Variable",
    "Identifier",
    "NamedCall",
    "Call",
    "PredicateSignature",
    "Clause",
    "PredicateArgs",
    "Compound",
    "Cut",
    "Sequence",
    "List",
    "Braces",
    "Parenthesis",
    "RestTokens",
    "IntAtom",
    "FloatAtom",
    "StringAtom",
    "CharAtom",
    "Separator",
    "BinaryOp",
  };
}
