java_lang_class('java.lang.Object').
java_lang_class('java.lang.Class').
java_lang_class('java.lang.ClassLoader').
java_lang_class('java.lang.Compiler').
java_lang_class('java.lang.String').
java_lang_class('java.lang.InheritableThreadLocal').
java_lang_class('java.lang.Integer').
java_lang_class('java.lang.Long').
java_lang_class('java.lang.Double').
java_lang_class('java.lang.Float').
java_lang_class('java.lang.Number').
java_lang_class('java.lang.Byte').
java_lang_class('java.lang.Boolean').
java_lang_class('java.lang.Character').
java_lang_class('java.lang.Short').
java_lang_class('java.lang.StringBuffer').
java_lang_class('java.lang.Void').
java_lang_class('java.lang.Thread').
java_lang_class('java.lang.ThreadLocal').
java_lang_class('java.lang.ThreadGroup').
java_lang_class('java.lang.Throwable').
java_lang_class('java.lang.Package').
java_lang_class('java.lang.System').
java_lang_class('java.lang.Math').
java_lang_class('java.lang.StrictMath').
java_lang_class('java.lang.Runtime').
java_lang_class('java.lang.RuntimePermission').
java_lang_class('java.lang.Process').
		
java_lang_class('java.lang.CharSequence').
java_lang_class('java.lang.Runnable').
java_lang_class('java.lang.Cloneable').
java_lang_class('java.lang.Comparable').
		
java_lang_class('java.lang.ArithmeticException').
java_lang_class('java.lang.ArrayIndexOutOfBoundsException').
java_lang_class('java.lang.ArrayStoreException').
java_lang_class('java.lang.ClassCastException').
java_lang_class('java.lang.ClassNotFoundException').
java_lang_class('java.lang.CloneNotSupportedException').
java_lang_class('java.lang.Exception').
java_lang_class('java.lang.IllegalAccessException').
java_lang_class('java.lang.IllegalArgumentException').
java_lang_class('java.lang.IllegalMonitorStateException').
java_lang_class('java.lang.IllegalStateException').
java_lang_class('java.lang.IllegalThreadStateException').
java_lang_class('java.lang.IndexOutOfBoundsException').
java_lang_class('java.lang.InstantiationException').
java_lang_class('java.lang.InterruptedException').
java_lang_class('java.lang.NegativeArraySizeException').
java_lang_class('java.lang.NoSuchFieldException').
java_lang_class('java.lang.NoSuchMethodException').
java_lang_class('java.lang.NullPointerException').
java_lang_class('java.lang.NumberFormatException').
java_lang_class('java.lang.RuntimeException').
java_lang_class('java.lang.SecurityException').
java_lang_class('java.lang.StringIndexOutOfBoundsException').
java_lang_class('java.lang.UnsupportedOperationException').
java_lang_class('java.lang.AbstractMethodError').
java_lang_class('java.lang.AssertionError').
java_lang_class('java.lang.ClassCircularityError').
java_lang_class('java.lang.ClassFormatError').
java_lang_class('java.lang.Error').
java_lang_class('java.lang.ExceptionInInitializerError').
java_lang_class('java.lang.IllegalAccessError').
java_lang_class('java.lang.IncompatibleClassChangeError').
java_lang_class('java.lang.InstantiationError').
java_lang_class('java.lang.InternalError').
java_lang_class('java.lang.LinkageError').
java_lang_class('java.lang.NoClassDefFoundError').
java_lang_class('java.lang.NoSuchFieldError').
java_lang_class('java.lang.NoSuchMethodError').
java_lang_class('java.lang.OutOfMemoryError').
java_lang_class('java.lang.StackOverflowError').
java_lang_class('java.lang.ThreadDeath').
java_lang_class('java.lang.UnknownError').
java_lang_class('java.lang.UnsatisfiedLinkError').
java_lang_class('java.lang.UnsupportedClassVersionError').
java_lang_class('java.lang.VerifyError').
java_lang_class('java.lang.VirtualMachineError').


update_java_lang :-
	forall(
		(java_lang_class(Class), 
		 not(globalIds(Class,_))),
		(
		    new_id(Id),
    		assert(user:globalIds(Class,Id)),
    		writeln(globalIds(Class,Id))
    	)).

:- update_java_lang.