/* Generated By:JJTree: Do not edit this line. ASTStringAtom.java */

package org.cs3.pl.parser.internal.classic;

public class ASTStringAtom extends ASTAtom {
  public ASTStringAtom(int id) {
    super(id);
  }

  public ASTStringAtom(PrologParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PrologParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
