package alice.tuprologx.runtime.corba;


/**
* org/alice/tuprologx/runtime/corba/Prolog.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from org/alice/tuprologx/runtime/corba/Prolog.idl
* venerdì 28 dicembre 2001 12.37.09 GMT+01:00
*/

public interface Prolog extends PrologOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Prolog
